"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k_m&5*2p$w-zox8o2a@+oy54m&q8%cprt$%af-9^8(vj!#^3hx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'custom_auth.mybackend.MobileBackend'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'custom_auth',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': []
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'project',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS' : {
            'sql_mode' : 'STRICT_ALL_TABLES'
        }
    }
}



# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'custom_auth.MyUser'


Kavenegar_API = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjY4ODQyNzlhY2Q2NTcxMGUxMmU0MjA4OGVhOWQ5ZGRlYTk2NjU5MTg2YzZhYmUyNWJiZWU2ZjNkOTBkMDMzYWY1YWU1MTg4NjQ1Njg0MjI3In0.eyJhdWQiOiIxIiwianRpIjoiNjg4NDI3OWFjZDY1NzEwZTEyZTQyMDg4ZWE5ZDlkZGVhOTY2NTkxODZjNmFiZTI1YmJlZTZmM2Q5MGQwMzNhZjVhZTUxODg2NDU2ODQyMjciLCJpYXQiOjE2NTMxMDg2OTcsIm5iZiI6MTY1MzEwODY5NywiZXhwIjoxNjg0NjQ0Njk3LCJzdWIiOiI5MjIxIiwic2NvcGVzIjpbXX0.gEr5TV-eon2bzNNUVSJAFmtjiH4a7rdII-MVX3G9cttfSC2REfYr0BJeFbdfi8L4PuHJFb_sdkE5hKyDeZEEwAFyOY9pv0s4pvBaJTMkX6PIP0LtV_2Y1SbRRGOR3InlLV1PKCM4qGDshsdjrqJniWQ-oV3Pbid8QsmTg3AKhavBHenjolSPOa2hguNbK5QmsmY8mKfqDnVWhu6BwEtrrMxfD82TrnHPOhFt7SsoTwkXBuShu5qpwzlo8K38fMnvcTxREI7mG49rqe0GRcCzVueAjuTU59H20VbzH2zoXdKkT-UQAYFuhR3Xpl1im6cWnJN561Xd_PuD3e6t7Ve4qIncZ9qGDcWmHk6xk0TMrdshZmXvFc0C_lEUNxG16osR-4NaOpUP2zli4sQn1yYmOobcCZXM2xq0GDZHB_ghWvQt8_QgKtu7Pmq1tDwEKdL-yRlz-LXUMd5Qd7jR-ifjzodrp0xlnELVM9Vk1QRNxPnC7ivUT0vnTw6lxppfgDD1ZhvtH3lZTmuZhu7BAGPLFhDqZzVn4UzUUAU2utmTDfPM7JAPNogO5ocz_tjTEMNrREQwJ_c4c2UEYTfl10QtD2BpheyXHPBAKuLBqyoAQz5e3Yl4JiJSjTY4PPh0tXgbW7rM4tiNOC-sYBmb_VISLCSJLvc3UPL-HYhSeqxwRrk'